// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    EventBadge: typeof import('./src/components/EventBadge.vue')['default']
    IFaRegularBellSlash: typeof import('~icons/fa-regular/bell-slash')['default']
    IGisEarthNetworkO: typeof import('~icons/gis/earth-network-o')['default']
    SiteQueue: typeof import('./src/components/SiteQueue.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
  }
}

export { }
