# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-19 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Monitored sites',
                'verbose_name': 'Monitored site',
                'ordering': ['name'],
            },
        ),
    ]
